### ISSUE TITLE
楼主测试该实现的ODS了么

### ISSUE THREAD

**Issue by CangHaiQingYue** [gengyanlei/HED#1]
如题，效果如何

**Comment by gengyanlei** [comment]
@CangHaiQingYue  
基于VGG16 的HF_FCN效果比HED效果好。我在本地训练分割数据集（二分类），HF_FCN比HED效果好。其他的方面就不清楚了。

**Comment by zchrissirhcz** [comment]
@gengyanlei 是在BSDS500上训练和测评吗？有具体ODS得分吗？

**Comment by gengyanlei** [comment]
@zchrissirhcz 
不是在BSDS数据集上，是在我们自己的分割数据集上。

**Comment by CangHaiQingYue** [comment]
恩恩@gengyanlei

**Comment by gengyanlei** [comment]
@CangHaiQingYue  ;  @zchrissirhcz
我的方向是语义分割方向，因此只是将这个网络应用在语义分割领域。没有应用到边界检测方面。所以严格的说，你们说的我均没有做过，我能回答的是在二分类语义分割上，hf_fcn 》 hed效果。

**Comment by CangHaiQingYue** [comment]
您电脑用的是哪款显卡0.0

**Comment by gengyanlei** [comment]
@CangHaiQingYue 
GTX1080

**Comment by CangHaiQingYue** [comment]
恩恩， 多谢啦@gengyanlei

**Comment by gengyanlei** [comment]
@CangHaiQingYue 
你好，非常不好意思。没有什么能够帮助到你的。

**Comment by CangHaiQingYue** [comment]
哈哈，客气了，您的这段代码就够我学习了，我是Tensorflow转过来的，刚开始看Pytorch。@gengyanlei

**Comment by gengyanlei** [comment]
@CangHaiQingYue 
我一开始用caffe，不太灵活，后面用tensorflow，现在用pytorch。还是pytorch更灵活些。
本人github下有pytorch-mnist-tutorial  （里面有更新学习率，设置不同学习率，fine-tune等）
以及pytorch下的一些网络。

**Comment by CangHaiQingYue** [comment]
嘿嘿。再次感谢了@gengyanlei

**Comment by gengyanlei** [comment]
@CangHaiQingYue 
忘记和你说了，pytorch也有可视化工具，visdom。我没怎么用到。你可以github搜一下。

**Comment by CangHaiQingYue** [comment]
@gengyanlei 恩恩，太极感激了！我之前在中文官网上看到有把pytorch和tensorboard联合用的，还没试过。  我下去学习一下visdom！！！

**Comment by gengyanlei** [comment]
@CangHaiQingYue 
不客气，pytorch 0.4版本及其以后，没有Variable和tensor的区别了，只需要在tensor里面设置require_grads即可。我也是后面才发现的。我用的就是pytorch 0.4。

**Comment by CangHaiQingYue** [comment]
@gengyanlei 恩恩， 我刚上手就是0.4了，没有管之前的Variable和tensor的区别，也算是绕过一个坑了， 哈哈哈。
